DOCKER_IMAGE: microservice-ethereum-user-actions
DOCKERFILE_PATH: ./cmd/microservice-ethereum-user-actions

SERVICES:
  - USER_ACTIONS_USDC:
      SERVICE_NAME: microservice-ethereum-user-actions-usdc
      
      ENV_FLU_WORKER_ID: production-ethereum-ropsten-microservice-ethereum-user-actions-usdc
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x2835bed5db82f84180ecbc7de7c1944e154b1035"
      ENV_FLU_ETHEREUM_TOKEN_NAME: USDC
      ENV_FLU_ETHEREUM_TOKEN_DECIMALS: 6

  - USER_ACTIONS_USDT:
      SERVICE_NAME: microservice-ethereum-user-actions-usdt
      
      ENV_FLU_WORKER_ID: production-ethereum-ropsten-microservice-ethereum-user-actions-usdt
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x26fc224b37952bd12c792425f242e0b0a55453a6"
      ENV_FLU_ETHEREUM_TOKEN_NAME: USDT
      ENV_FLU_ETHEREUM_TOKEN_DECIMALS: 6

  - USER_ACTIONS_DAI:
      SERVICE_NAME: microservice-ethereum-user-actions-dai
      
      ENV_FLU_WORKER_ID: production-ethereum-ropsten-microservice-ethereum-user-actions-dai
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x5ba8d8e005ade3a8333cf85c3bf2a0869d606569"
      ENV_FLU_ETHEREUM_TOKEN_NAME: DAI
      ENV_FLU_ETHEREUM_TOKEN_DECIMALS: 18
