anchor_version = "0.22.1"
solana_version = "1.9.12"

[features]
seeds = false
[programs.localnet]
tribeca_data_store = "HdSHLoG6gbQ7tkMvB87QraPpdxF9bnfNobbjnZxKviRS"

[programs.devnet]
tribeca_data_store = "HdSHLoG6gbQ7tkMvB87QraPpdxF9bnfNobbjnZxKviRS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/glo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
