DOCKER_IMAGE: microservice-ethereum-application-server
DOCKERFILE_PATH: ./cmd/microservice-ethereum-application-server
SECRET_FLU_ETHEREUM_APPLICATION_CONTRACTS: /fluidity/ethereum/application_contracts
SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/ethereum/http_url

SERVICES:
  - APPSERVER_USDT:
      SERVICE_NAME: microservice-ethereum-application-server-usdt
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-application-server-usdt
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x777B135370b35737655a3BA7ca85bD0F08502313"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 6

  - APPSERVER_USDC:
      SERVICE_NAME: microservice-ethereum-application-server-usdc
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-application-server-usdc
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x815451bbD6C49e43fB1b614bf405E2A69A95D3Fc"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 6

  - APPSERVER_DAI:
      SERVICE_NAME: microservice-ethereum-application-server-dai
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-application-server-dai
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xF7449745797B4A5932055aECF5c80AE504Bc1495"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 18

  - APPSERVER_TUSD:
      SERVICE_NAME: microservice-ethereum-application-server-tusd
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-application-server-tusd
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xA49BB086ca9Fa2DFbb9feE1b2033112485b743D4"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 18



