SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/ropsten/http_url
DOCKER_IMAGE: microservice-ethereum-worker-server
DOCKERFILE_PATH: ./cmd/microservice-ethereum-worker-server

SERVICES:
  - WORKER_SERVER_USDT:
      SERVICE_NAME: microservice-ethereum-worker-server-usdt
      
      ENV_FLU_WORKER_ID: production-ethereum-ropsten-microservice-ethereum-worker-server-usdt
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: 0x26fc224b37952bd12c792425f242e0b0a55453a6
      ENV_FLU_ETHEREUM_TOKEN_BACKEND: compound
      ENV_FLU_ETHEREUM_UNISWAP_ANCHORED_VIEW_ADDR: 0xbef4e076a995c784be6094a432b9ca99b7431a3f
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: USDT
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 6
      ENV_FLU_ETHEREUM_CTOKEN_ADDR: 0xF6958Cf3127e62d3EB26c79F4f45d3F3b2CcdeD4
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdt
      ENV_FLU_ETHEREUM_REDIS_APY_MOVING_AVERAGE_KEY: ethereum.worker.usdt.apy.moving-average

  - WORKER_SERVER_USDC:
      SERVICE_NAME: microservice-ethereum-worker-server-usdc
      
      ENV_FLU_WORKER_ID: production-ethereum-ropsten-microservice-ethereum-worker-server-usdc
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: 0x2835bed5db82f84180ecbc7de7c1944e154b1035
      ENV_FLU_ETHEREUM_TOKEN_BACKEND: compound
      ENV_FLU_ETHEREUM_UNISWAP_ANCHORED_VIEW_ADDR: 0xbef4e076a995c784be6094a432b9ca99b7431a3f
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: USDC
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 6
      ENV_FLU_ETHEREUM_CTOKEN_ADDR: 0x2973e69b20563bcc66dC63Bde153072c33eF37fe
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdc
      ENV_FLU_ETHEREUM_REDIS_APY_MOVING_AVERAGE_KEY: ethereum.worker.usdc.apy.moving-average

  - WORKER_SERVER_DAI:
      SERVICE_NAME: microservice-ethereum-worker-server-dai
      
      ENV_FLU_WORKER_ID: production-ethereum-ropsten-microservice-ethereum-worker-server-dai
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: 0x5ba8d8e005ade3a8333cf85c3bf2a0869d606569
      ENV_FLU_ETHEREUM_TOKEN_BACKEND: compound
      ENV_FLU_ETHEREUM_UNISWAP_ANCHORED_VIEW_ADDR: 0xbef4e076a995c784be6094a432b9ca99b7431a3f
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: DAI
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 18
      ENV_FLU_ETHEREUM_CTOKEN_ADDR: 0xbc689667c13fb2a04f09272753760e38a95b998c
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.dai
