---

version: "2"

services:
  redis:
    image: redis

  rabbitmq:
    image: rabbitmq

  backend:
    image: fluidity/ethereum-testnet-faucet-backend
    environment:
      - FLU_WEB_LISTEN_ADDR=:80
    depends_on:
      - rabbitmq
      - redis

  frontend:
    image: fluidity/ethereum-testnet-faucet-frontend

  proxy:
    image: fluidity/api-proxy-docker:latest
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
