SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/ropsten/http_url
DOCKER_IMAGE: microservice-ethereum-worker-client
DOCKERFILE_PATH: ./cmd/microservice-ethereum-worker-client

SERVICES:
  - WORKER_CLIENT_USDT:
      SERVICE_NAME: microservice-ethereum-worker-client-usdt
      
      ENV_FLU_WORKER_ID: production-ethereum-ropsten-microservice-ethereum-worker-server-usdt
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: 0x2835bed5db82f84180ecbc7de7c1944e154b1035
      ENV_FLU_ETHEREUM_GAS_LIMIT: 8000000
      ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdt
      SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ropsten/usdt/private_key

  - WORKER_CLIENT_USDC:
      SERVICE_NAME: microservice-ethereum-worker-client-usdc

      ENV_FLU_WORKER_ID: production-ethereum-ropsten-microservice-ethereum-worker-server-usdc
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: 0x26fc224b37952bd12c792425f242e0b0a55453a6
      ENV_FLU_ETHEREUM_GAS_LIMIT: 8000000
      ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdc
      SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ropsten/usdc/private_key

  - WORKER_CLIENT_DAI:
      SERVICE_NAME: microservice-ethereum-worker-client-dai
      
      ENV_FLU_WORKER_ID: production-ethereum-ropsten-microservice-ethereum-worker-server-dai
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: 0x5ba8d8e005ade3a8333cf85c3bf2a0869d606569
      ENV_FLU_ETHEREUM_GAS_LIMIT: 8000000
      ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.dai
      SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ropsten/dai/private_key

