# Setup Webapp Network Drivers
[[drivers.solana]]
label = "Solana"
testnet = false
rpc = { http = 'FLU_SOL_RPC_HTTP', ws = 'FLU_SOL_RPC_WS' }
server = "https://api.solana.fluidity.money"

[[drivers.arbitrum]]
label = "Arbitrum"
testnet = false
rpc = { http = "FLU_ARB_RPC_HTTP", ws = "FLU_ARB_RPC_WS" }

[[drivers.polygon_zk]]
label = "Polygon ZK"
testnet = false
rpc = { http = "FLU_POLYZK_RPC_HTTP", ws = "FLU_POLYZK_RPC_WS" }

[[drivers.hasura]]
label= "Hasura"
testnet = false
rpc = { http = "FLU_HASURA_RPC_HTTP", ws = "FLU_HASURA_RPC_WS" }
secret = "FLU_HASURA_SECRET"

[config.solana]
explorer = "https://explorer.solana.com"
fluidAssets = [
    "Ez2zVjw85tZan1ycnJ5PywNNxR6Gm4jbXQtZKyQNu3Lv",
]

[[config.solana.tokens]]
symbol = "USDC"
name = "USDC Native"
logo = "/assets/tokens/usdc.svg"
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
colour = "#2775ca"
decimals = 6
enabled = true

[[config.solana.tokens]]
symbol = "fUSDC"
name = "Fluid USDC Native"
logo = "/assets/tokens/fUSDC.svg"
address = "Ez2zVjw85tZan1ycnJ5PywNNxR6Gm4jbXQtZKyQNu3Lv"
colour = "#2775ca"
isFluidOf = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
obligationAccount = "J6ZHkcCiAKSKTmoUZzozZ2L1Wwm34WF2VQamyu2Sno6A"
dataAccount = "Gy6weHjgTxqFqosH1sGdECC2jG4j9h8t347KrumsQzce"
decimals = 6
enabled = true

[config.arbitrum]
explorer = "https://etherscan.io"
fluidAssets = [
    "0x4CFA50B7Ce747e2D61724fcAc57f24B748FF2b2A",
    "0xC9FA90D24B7103Ad2215DE52afec5e1E4C7a6e62",
    "0x1b40e7812E75D02Eef97E4399c33865D2Ff5952b",
]

[[config.arbitrum.tokens]]
symbol = "USDC"
name = "USDC Native"
logo = "/assets/tokens/usdc.svg"
address = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
colour = "#2775ca"
decimals = 6
enabled = true

[[config.arbitrum.tokens]]
symbol = "fUSDC"
name = "Fluid USDC Native"
logo = "/assets/tokens/fUSDC.svg"
address = "0x4CFA50B7Ce747e2D61724fcAc57f24B748FF2b2A"
colour = "#2775ca"
isFluidOf = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
decimals = 6
enabled = true

[[config.arbitrum.tokens]]
symbol = "USDT"
name = "Tether USD"
logo = "/assets/tokens/usdt.svg"
address = "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
colour = "#12946c"
decimals = 6
enabled = true

[[config.arbitrum.tokens]]
symbol = "fUSDT"
name = "Fluid USDT"
logo = "/assets/tokens/fUSDT.svg"
address = "0xC9FA90D24B7103Ad2215DE52afec5e1E4C7a6e62"
colour = "#12946c"
isFluidOf = "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
decimals = 6
enabled = true

[[config.arbitrum.tokens]]
symbol = "DAI"
name = "Dai Stablecoin"
logo = "/assets/tokens/dai.svg"
address = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
colour = "#825902"
decimals = 18
enabled = true

[[config.arbitrum.tokens]]
symbol = "fDAI"
name = "Fluid DAI"
logo = "/assets/tokens/fDAI.svg"
address = "0x1b40e7812E75D02Eef97E4399c33865D2Ff5952b"
colour = "#825902"
isFluidOf = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
decimals = 18
enabled = true

[[config.arbitrum.tokens]]
symbol = "wETH"
name = "Wrapped Ether"
logo = "/assets/tokens/weth.svg"
address = "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"
colour = "#eb2077"
decimals = 18
enabled = false

[config.polygon_zk]
explorer = "https://zkevm.polygonscan.com"
fluidAssets = [
    "0x74ad340fE9C506700B6ca039BDfA36cFD5dcc18C",
]

[[config.polygon_zk.tokens]]
symbol = "USDC"
name = "USDC Native"
logo = "/assets/tokens/usdc.svg"
address = "0xA8CE8aee21bC2A48a5EF670afCc9274C7bbbC035"
colour = "#2775ca"
decimals = 6
enabled = true

[[config.polygon_zk.tokens]]
symbol = "fUSDC"
name = "Fluid USDC Native"
logo = "/assets/tokens/fUSDC.svg"
address = "0x74ad340fE9C506700B6ca039BDfA36cFD5dcc18C"
colour = "#2775ca"
isFluidOf = "0xA8CE8aee21bC2A48a5EF670afCc9274C7bbbC035"
decimals = 6
enabled = true

# sol providers
[liquidity_providers.solana]

[[liquidity_providers.solana.providers]]
name= "solend"

[liquidity_providers.solana.providers.link]
fUSDC = "https://www.solend.fi/"
fUSDT = "https://www.solend.fi/"

[[liquidity_providers.solana.providers]]
name= "orca"

[liquidity_providers.solana.providers.link]
fUSDC = "https://www.orca.so/"
fUSDT = "https://www.orca.so/"

[[liquidity_providers.solana.providers]]
name= "saber"

[liquidity_providers.solana.providers.link]
fUSDC = "https://www.saber.so/"
fUSDT = "https://www.saber.so/"

[[liquidity_providers.solana.providers]]
name= "jupiter"

[liquidity_providers.solana.providers.link]
fUSDC = "https://www.jup.ag/"
fUSDT = "https://www.jup.ag/"

[liquidity_providers.arbitrum]

[[liquidity_providers.arbitrum.providers]]
name= "uniswap"

[liquidity_providers.arbitrum.providers.link]
fUSDC = "https://app.uniswap.org/#/add/0xaf88d065e77c8cC2239327C5EDb3A432268e5831/0x4CFA50B7Ce747e2D61724fcAc57f24B748FF2b2A/500"

[[liquidity_providers.arbitrum.providers]]
name= "camelot"

[liquidity_providers.arbitrum.providers.link]
fUSDC = "https://app.camelot.exchange/liquidity/?token1=0xaf88d065e77c8cC2239327C5EDb3A432268e5831&token2=0x4CFA50B7Ce747e2D61724fcAc57f24B748FF2b2A"

[[liquidity_providers.arbitrum.providers]]
name= "Chronos"

[liquidity_providers.arbitrum.providers.link]
fUSDC = "https://app.chronos.exchange/liquidity"

[[config.ethereum.wallets]]
name = "Browser"
id = "metamask"
description = "Browser based wallets like Metamask, Brave, Coinbase Wallet and Opera."
logo = "/assets/wallets/eth_browser.svg"

[[config.ethereum.wallets]]
name = "WalletConnect"
id = "walletconnect"
description = "WalletConnect allows you to connect your wallet to any dApp using a QR code."
logo = "/assets/wallets/walletconnect.svg"

[[config.ethereum.wallets]]
name = "OKX Wallet"
id = "okxwallet"
description = "OKX Wallet allows you to connect your wallet to any dApp, and supports a variety of blockchains."
logo = "/assets/wallets/okx.svg"

[[config.ethereum.wallets]]
name = "Coin98"
id = "coin98"
description = "Store multi-chain Cryptoassets with Coin98 Wallet."
logo = "/assets/wallets/coin98.svg"

[[contract.solana]]
name = "Mainnet"
address = "HEvunKKgzf4SMZimVMET6HuzAyfGJS4ZMShUz94KLUdR"

[contract.prize_pool]
ethereum = "0xD3E24D732748288ad7e016f93B1dc4F909Af1ba0"
arbitrum = "0x9e48603b87930eD3EC6eB599413C4d423D92C822"
solana = ""
polygon_zk = "0xDB6d7F5aF3caDFEBBB86DD627C68fdC58cdEB91B"

[contract.staking]
ethereum = ""
arbitrum = "0x0935a031F28F8B3E600A2E5e1f48920eD206e2d0"
solana = ""
polygon_zk = ""

[contract.eac_aggregator_proxy]
ethereum = ""
arbitrum = "0x639Fe6ab55C921f74e7fac1ee960C0B6293ba612"
solana = ""
polygon_zk = ""

[contract.registry]
ethereum = ""
arbitrum = "0x28EE3aCA2DAA47a7585C5c579dBb0998C08f845d"
solana = ""
polygon_zk = ""
