SERVICES:
  - CONNECTOR_COMMON_USER_ACTIONS_TIMESCALE:
      SERVICE_NAME: connector-common-user-actions-timescale
      DOCKERFILE_PATH: ./cmd/connector-common-user-actions-timescale
      ENV_FLU_WORKER_ID: production-solana-connector-common-user-actions-timescale

  - CONNECTOR_COMMON_PRIZE_POOL_POSTGRES:
      SERVICE_NAME: connector-common-prize-pool-postgres
      DOCKERFILE_PATH: ./cmd/connector-common-prize-pool-postgres
      ENV_FLU_WORKER_ID: production-solana-connector-common-prize-pool-postgres

  - CONNECTOR_COMMON_WINNERS_TIMESCALE:
      SERVICE_NAME: connector-common-winners-timescale
      DOCKERFILE_PATH: ./cmd/connector-common-winners-timescale
      ENV_FLU_WORKER_ID: production-solana-connector-common-prize-pool

  - CONNECTOR_COMMON_EMISSIONS_TIMESCALE:
      SERVICE_NAME: connector-common-emissions-timescale
      DOCKERFILE_PATH: ./cmd/connector-common-emissions-timescale
      ENV_FLU_WORKER_ID: production-solana-connector-common-emissions-timescale