---
version: "3"

services:
  ethereum.fluidity.money-frontend:
    build:
      context: ../web/ethereum.fluidity.money
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_API_URL: ${FLU_FRONTEND_API_URL}
        REACT_APP_WALLET_CONNECT_GETH_URI: ${FLU_FRONTEND_GETH_URL}
        REACT_APP_WEBSOCKET: ${FLU_FRONTEND_WS_URL}
        REACT_APP_CHAIN_ID: ${FLU_FRONTEND_CHAIN_ID}
        REACT_APP_WALLET_CONNECT_GETH_URI: ${FLU_FRONTEND_GETH_URL}
        REACT_APP_TOKEN_CONFIG_FILE: ${FLU_FRONTEND_TOKEN_FILE}
    ports:
      - 127.0.0.1:8080:80

  ethereum.fluidity.money-backend:
    build:
      context: ../web/ethereum.fluidity.money
      dockerfile: Dockerfile.backend
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ethereum.fluidity.money-backend
    ports:
      - 127.0.0.1:8081:80
