---
version: "3"

services:
  microservice-solana-transactions:
    build:
      context: ../cmd/microservice-solana-transactions
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-microservice-solana-transactions
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_SOLANA_RPC_URL: ${FLU_SOLANA_RPC_URL}
      FLU_SOLANA_SABER_RPC_URL: ${FLU_SOLANA_SABER_RPC_URL}
      FLU_SOLANA_SABER_SWAP_PROGRAM_ID: ${FLU_SOLANA_SABER_SWAP_PROGRAM_ID}
      FLU_SOLANA_SOL_PYTH_PUBKEY: ${FLU_SOLANA_SOL_PYTH_PUBKEY}
    deploy:
      mode: replicated
      replicas: 50
    restart: unless-stopped

  microservice-solana-user-actions-usdc:
    build:
      context: ../cmd/microservice-solana-user-actions
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-microservice-solana-user-actions-usdc
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_SOLANA_PROGRAM_ID: ${FLU_SOLANA_PROGRAM_ID}
      FLU_SOLANA_FLUID_MINT_PUBKEY: ${FLU_SOLANA_FLUID_MINT_PUBKEY_USDC}
      FLU_SOLANA_PDA_PUBKEY: ${FLU_SOLANA_PDA_PUBKEY_USDC}
      FLU_SOLANA_TOKEN_SHORT_NAME: ${FLU_SOLANA_TOKEN_SHORT_NAME_USDC}
      FLU_SOLANA_TOKEN_DECIMALS: ${FLU_SOLANA_TOKEN_DECIMALS_USDC}
    deploy:
      mode: replicated
      replicas: 50
    restart: unless-stopped
    depends_on:
      - rabbitmq

  microservice-solana-user-actions-usdt:
    build:
      context: ../cmd/microservice-solana-user-actions
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: microservice-solana-user-actions-usdt
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_SOLANA_PROGRAM_ID: ${FLU_SOLANA_PROGRAM_ID}
      FLU_SOLANA_FLUID_MINT_PUBKEY: ${FLU_SOLANA_FLUID_MINT_PUBKEY_USDT}
      FLU_SOLANA_PDA_PUBKEY: ${FLU_SOLANA_PDA_PUBKEY_USDT}
      FLU_SOLANA_TOKEN_SHORT_NAME: ${FLU_SOLANA_TOKEN_SHORT_NAME_USDT}
      FLU_SOLANA_TOKEN_DECIMALS: ${FLU_SOLANA_TOKEN_DECIMALS_USDT}
    deploy:
      mode: replicated
      replicas: 50
    restart: unless-stopped
    depends_on:
      - rabbitmq

