---
version: "3"

services:
  connector-solana-amqp:
    build:
      context: ../cmd/connector-solana-amqp
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-connector-solana-amqp
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_SOLANA_WS_URL: ${FLU_SOLANA_WS_URL}
      FLU_SOLANA_RPC_URL: ${FLU_SOLANA_RPC_URL}
      FLU_SOLANA_STARTING_SLOT: ${FLU_SOLANA_STARTING_SLOT}
    restart: unless-stopped

  connector-solana-tvl-amqp:
    build:
      context: ../cmd/connector-solana-tvl-amqp
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-connector-solana-tvl-amqp
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_SOLANA_WS_URL: ${FLU_SOLANA_WS_URL}
      FLU_SOLANA_RPC_URL: ${FLU_SOLANA_RPC_URL}
      FLU_SOLANA_PROGRAM_ID: ${FLU_SOLANA_PROGRAM_ID}
      FLU_SOLANA_TVL_DATA_PUBKEY: ${FLU_SOLANA_TVL_DATA_PUBKEY}
      FLU_SOLANA_SOLEND_PUBKEY: ${FLU_SOLANA_TVL_SOLEND_PUBKEY}
      FLU_SOLANA_OBLIGATION_PUBKEY: ${FLU_SOLANA_OBLIGATION_PUBKEY}
      FLU_SOLANA_RESERVE_PUBKEY: ${FLU_SOLANA_RESERVE_PUBKEY}
      FLU_SOLANA_PYTH_PUBKEY: ${FLU_SOLANA_PYTH_PUBKEY}
      FLU_SOLANA_SWITCHBOARD_PUBKEY: ${FLU_SOLANA_SWITCHBOARD_PUBKEY}
      FLU_SOLANA_TVL_PAYER_PRIKEY: ${FLU_SOLANA_TVL_PAYER_PRIKEY}
      FLU_SOLANA_SOLEND_PROGRAM_ID: ${FLU_SOLANA_SOLEND_PROGRAM_ID}
