---
version: "3"

services:
  ethereum.fluidity.money-frontend:
    build:
      context: ../web/ethereum.fluidity.money
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_API_URL: http://localhost:8081
        REACT_APP_WALLET_CONNECT_GETH_URI: http://contracts-ethereum:8545
        REACT_APP_WEBSOCKET: ws://localhost:8081/updates
        REACT_APP_CHAIN_ID: 31337
        REACT_APP_WALLET_CONNECT_GETH_URI: ws://contracts-ethereum:8545
        REACT_APP_TOKEN_CONFIG_FILE: testing-tokens.json
    ports:
      - 8080:80

  ethereum.fluidity.money-backend:
    build:
      context: ../web/ethereum.fluidity.money
      dockerfile: Dockerfile.backend
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ethereum.fluidity.money-backend
    ports:
      - 8081:80
