---
version: "3"

services:
  microservice-amqp-copy-messages-testing:
    build:
      context: ../cmd/microservice-amqp-copy-messages
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-microservice-amqp-copy-messages
      FLU_AMQP_COPY_FROM_EXCHANGE: ${FLU_AMQP_COPY_FROM_EXCHANGE_TESTING}
      FLU_AMQP_COPY_FROM_TOPIC_NAME: ${FLU_AMQP_COPY_FROM_TOPIC_NAME_TESTING}
      FLU_AMQP_COPY_FROM_URI: ${FLU_AMQP_COPY_FROM_URI_TESTING}
      FLU_AMQP_COPY_TO_EXCHANGE: ${FLU_AMQP_COPY_TO_EXCHANGE_TESTING}
      FLU_AMQP_COPY_TO_TOPIC_NAME: ${FLU_AMQP_COPY_TO_TOPIC_NAME_TESTING}
      FLU_AMQP_COPY_TO_URI: ${FLU_AMQP_COPY_TO_URI_TESTING}

  microservice-amqp-copy-messages-production:
    build:
      context: ../cmd/microservice-amqp-copy-messages
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-microservice-amqp-copy-messages
      FLU_AMQP_COPY_FROM_EXCHANGE: ${FLU_AMQP_COPY_FROM_EXCHANGE_PRODUCTION}
      FLU_AMQP_COPY_FROM_TOPIC_NAME: ${FLU_AMQP_COPY_FROM_TOPIC_NAME_PRODUCTION}
      FLU_AMQP_COPY_FROM_URI: ${FLU_AMQP_COPY_FROM_URI_PRODUCTION}
      FLU_AMQP_COPY_TO_EXCHANGE: ${FLU_AMQP_COPY_TO_EXCHANGE_PRODUCTION}
      FLU_AMQP_COPY_TO_TOPIC_NAME: ${FLU_AMQP_COPY_TO_TOPIC_NAME_PRODUCTION}
      FLU_AMQP_COPY_TO_URI: ${FLU_AMQP_COPY_TO_URI_PRODUCTION}
