---
version: "3"

services:
  connector-common-user-actions-timescale:
    build:
      context: ../cmd/connector-common-user-actions-timescale
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: connector-common-user-actions-timescale
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
    depends_on:
      - timescale

  connector-common-prize-pool-postgres:
    build:
      context: ../cmd/connector-common-prize-pool-postgres
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: connector-common-prize-pool-postgres
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_ETHEREUM_HTTP_URL: ${FLU_ETHEREUM_HTTP_URL}
    depends_on:
      - postgres
