---
version: "3"

services:
  worker-solana-server-usdc:
    command: solana-server
    build:
      context: ../cmd/microservice-solana-worker
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: worker-solana-server-usdc
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_SOLANA_RPC_URL: ${FLU_SOLANA_RPC_URL}
      FLU_SOLANA_PROGRAM_ID: ${FLU_SOLANA_PROGRAM_ID}
      FLU_SOLANA_FLUID_MINT_PUBKEY: ${FLU_SOLANA_FLUID_MINT_PUBKEY_USDC}
      FLU_SOLANA_TVL_DATA_PUBKEY: ${FLU_SOLANA_TVL_DATA_PUBKEY}
      FLU_SOLANA_SOLEND_PROGRAM_ID: ${FLU_SOLANA_SOLEND_PROGRAM_ID}
      FLU_SOLANA_OBLIGATION_PUBKEY: ${FLU_SOLANA_OBLIGATION_PUBKEY_USDC}
      FLU_SOLANA_RESERVE_PUBKEY: ${FLU_SOLANA_RESERVE_PUBKEY_USDC}
      FLU_SOLANA_PYTH_PUBKEY: ${FLU_SOLANA_PYTH_PUBKEY_USDC}
      FLU_SOLANA_SWITCHBOARD_PUBKEY: ${FLU_SOLANA_SWITCHBOARD_PUBKEY_USDC}
      FLU_SOLANA_PAYER_PRIKEY: ${FLU_SOLANA_WORKER_PRIVATE_KEY}
      FLU_DEBUG_FAKE_PAYOUTS: ${FLU_DEBUG_FAKE_PAYOUTS}
      FLU_SOLANA_TOKEN_DECIMALS: ${FLU_SOLANA_TOKEN_DECIMALS_USDC}
      FLU_SOLANA_TOKEN_NAME: ${FLU_SOLANA_TOKEN_SHORT_NAME_USDC}
    depends_on:
      - rabbitmq

  worker-solana-server-usdt:
    command: solana-server
    build:
      context: ../cmd/microservice-solana-worker
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: worker-solana-server-usdt
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_SOLANA_RPC_URL: ${FLU_SOLANA_RPC_URL}
      FLU_SOLANA_PROGRAM_ID: ${FLU_SOLANA_PROGRAM_ID}
      FLU_SOLANA_FLUID_MINT_PUBKEY: ${FLU_SOLANA_FLUID_MINT_PUBKEY_USDT}
      FLU_SOLANA_TVL_DATA_PUBKEY: ${FLU_SOLANA_TVL_DATA_PUBKEY}
      FLU_SOLANA_SOLEND_PROGRAM_ID: ${FLU_SOLANA_SOLEND_PROGRAM_ID}
      FLU_SOLANA_OBLIGATION_PUBKEY: ${FLU_SOLANA_OBLIGATION_PUBKEY_USDT}
      FLU_SOLANA_RESERVE_PUBKEY: ${FLU_SOLANA_RESERVE_PUBKEY_USDT}
      FLU_SOLANA_PYTH_PUBKEY: ${FLU_SOLANA_PYTH_PUBKEY_USDT}
      FLU_SOLANA_SWITCHBOARD_PUBKEY: ${FLU_SOLANA_SWITCHBOARD_PUBKEY_USDT}
      FLU_SOLANA_PAYER_PRIKEY: ${FLU_SOLANA_WORKER_PRIVATE_KEY}
      FLU_DEBUG_FAKE_PAYOUTS: ${FLU_DEBUG_FAKE_PAYOUTS}
      FLU_SOLANA_TOKEN_DECIMALS: ${FLU_SOLANA_TOKEN_DECIMALS_USDT}
      FLU_SOLANA_TOKEN_NAME: ${FLU_SOLANA_TOKEN_SHORT_NAME_USDT}
    depends_on:
      - rabbitmq
