

SERVICES:
  - SLURP:
      SERVICE_NAME: microservice-common-amqp-http-long-poll-basic
      DOCKERFILE_PATH: ./cmd/microservice-common-amqp-http-long-poll-basic
      TARGET_GROUP: flu-dev-ropsten-slurp-tg
      SECRET_FLU_LONG_POLL_LOGINS: /fluidity/slurp_server
  