
name: "Docker Compose build"

on:
  push:
    branches:
      - develop-*
      - staging-*
      - production-*

jobs:
  build:
    name: "Docker Compose build"
    runs-on: ubuntu-18.04
    steps:
      - name: "Load Git-related envs"
        id: configure
        run: |
          VERSION=$(echo $GITHUB_REF | sed -e "s/^refs\/tags\/v//")
          echo ::set-output name=version::$VERSION

      - name: "Checkout repo"
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GIT_CHECKOUT_TOKEN }}
          lfs: true

      - name: "Beginning Slack notification"
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_TITLE: "Starting to build ${{ steps.ecr_repo.outputs.REPO_NAME }}"
          SLACK_MESSAGE: "Commit: ${{ github.sha }}/${{ steps.get_version.outputs.VERSION }}"
          SLACK_COLOR: "yellow"
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_NOTIFICATIONS }}

      - name: "Build the repo"
        run: ./scripts/docker-compose-all.sh

      - name: "Beginning Slack notification"
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_TITLE: "${{ steps.ecr_repo.outputs.REPO_NAME }} built!"
          SLACK_MESSAGE: "Commit: ${{ github.sha }}/${{ steps.get_version.outputs.VERSION }}"
          SLACK_COLOR: "green"
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_NOTIFICATIONS }}
