name: Run Tests (develop)

on: 
  pull_request:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: isbang/compose-action@v1.3.2
        with:
          compose-file: "./tests/infrastructure/docker-compose.yml"
      - uses: cedrickring/golang-action@1.7.0
        with:
          args: go mod download -x
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install semgrep
      - run: make test
