name: Mainnet (Auto)

on:
  pull_request:
    branches:
      - production
    types:
      - closed

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: mainnet

jobs:
 build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: mainnet
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.FLU_AWS_GITHUB_OIDC_ROLE }}
          role-duration-seconds: 7200 #seconds
      - name: Get Diff
        id: diff
        uses: ./scripts/actions
        with:
          command: |
            flu get-diff --environment $ENVIRONMENT --tag $GITHUB_SHA
      - name: Build
        id: build
        uses: ./scripts/actions
        with:
          command: |
            flu build-diff --environment $ENVIRONMENT --tag $GITHUB_SHA
      - name: Deploy
        id: deploy
        uses: ./scripts/actions
        with:
          command: |
            flu deploy-diff --environment $ENVIRONMENT --tag $GITHUB_SHA
      - name: Discord
        uses: ./scripts/actions
        if: always()
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with: 
          command: |
            flu send-discord --webhook-url ${{ secrets.FLU_CI_DISCORD_WEBHOOK_URL }} --status ${{ job.status }}

