name: Fluidity CI/CD (Test Service)

on:
  push:
    branches:
      - develop-ci-slack-notif
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.FLU_CI_SLACK_WEBHOOK_URL }}
      NETWORK: ethereum
      GROUP: worker-server
      SERVICE: WORKER_SERVER_USDT
      ENVIRONMENT: dev
      BUILD_BASE: false
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.FLU_DEV_AWS_GITHUB_OIDC_ROLE }}
      - name: Build
        id: build
        uses: ./scripts/actions
        with:
          command: |
            flu build-docker \
              --network ${{ env.NETWORK }} \
              --group ${{ env.GROUP }} \
              --service ${{ env.SERVICE }} \
              --environment ${{ env.ENVIRONMENT }} \
              --tag $GITHUB_SHA \
              --build-common ${{ env.BUILD_BASE }}
      - name: Deploy
        id: deploy
        uses: ./scripts/actions
        with:
          command: |
            flu deploy-service \
              --network ${{ env.NETWORK }} \
              --group ${{ env.GROUP }} \
              --service ${{ env.SERVICE }} \
              --environment ${{ env.ENVIRONMENT }} \
              --tag $GITHUB_SHA \
              --debug false
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#develop-ci-alerts'
        if: always()


