name: Rollback Staging Test (Manual)

on:
  workflow_dispatch:
    inputs:
      rollbackTo:
        type: string
        description: 'Commit Id'
        required: true
      environment:
        type: choice
        description: 'Environment'
        options:
          - 'dev'
      build_root_container:
        type: boolean
        description: 'Build root-container'
        default: true
      build_build_container:
        type: boolean
        description: 'Build build-container'
        default: true
      rollback_timescale:
        type: boolean
        description: 'Rollback Timescale DB'
        default: false
      rollback_posgres:
        type: boolean
        description: 'Rollback Postgres DB'
        default: false
      skip_app_rollback:
        type: boolean
        description: 'Skip rollback-app'
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  rollback-app:
    if: ${{ github.event.inputs.skip_app_rollback == 'false' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
          lfs: true
          ref: ${{ github.event.inputs.rollbackTo }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.FLU_AWS_GITHUB_OIDC_ROLE }}
          role-duration-seconds: 7200 #seconds
      - name: Build
        id: build
        uses: ./scripts/actions
        with:
          command: |
            echo $GITHUB_SHA

      - name: Deploy
        id: deploy
        uses: ./scripts/actions
        with:
          command: |
            echo $GITHUB_SHA

  rollback-db:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.FLU_AWS_GITHUB_OIDC_ROLE }}
          role-duration-seconds: 7200 #seconds
      - name: Rollback Database
        id: db
        uses: ./scripts/actions
        with:
          command: |
            echo $GITHUB_SHA

            flu rollback-db \
              --network ${{ github.event.inputs.network }} \
              --environment ${{ github.event.inputs.environment }} \
              --rollback-timescaledb ${{ github.event.inputs.rollback_timescale }} \
              --rollback-postgresdb ${{ github.event.inputs.rollback_postgres }} \
              --tag $GITHUB_SHA


