name: Staging (npm test)

on:
  pull_request:
    branches:
      - develop-webapp-remix

permissions:
  id-token: write
  contents: write
  packages: write

env:
  ENVIRONMENT: dev

jobs:
  npm-test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Test
        run: |
          npm install
          npm test
