name: Webapp Test (staging)

on:
  pull_request:
    branches:
      - develop

permissions:
  id-token: write
  contents: write
  packages: write

env:
  ENVIRONMENT: dev

jobs:
  npm-test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Test
        working-directory: web/app.fluidity.money
        run: |
          npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm install
          npm test
